### PR TITLE
Fix GCC build

### LINKED ISSUE #514: Building C++ SDK with GCC fails due to template specialization
**Description**

Building C++ SDK with GCC fails due to template specialization.

- Version: 0.9.0
- Platform: Linux x86_64 (Ubuntu 22.04), gcc 11.4.0 (also tested with gcc 12.3.0)

**Steps To Reproduce**

```
cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -S ./cpp -B ./build -G Ninja
ninja -C build
```

This fails with build errors due to template specialization in paramter.cpp

Whereas configuring with a clang toolchain succeeds.

```
cmake -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -S ./cpp -B ./build -G Ninja
```

### PR DESCRIPTION
**Pull request by jtbandes**
### Changelog
C++: fixed building with GCC

### Docs

None

### Description

Fixes FG-12176
Fixes #514 

It is 2025, and GCC does not support a C++17 feature 🙃 

It seems like maybe we switched to clang for all platforms in #383 because of this issue?

### CODE REVIEW

**Comment by jtbandes** [comment]
Seems to work but I'll need some help from someone who knows more about doxygen

**Comment by amacneil** [comment]
Can we add to CI?

File: cpp/Makefile [hunk 1]
```diff
@@ -30,8 +30,6 @@ clean:
 .PHONY: build
 build:
 	cmake \
-		-DCMAKE_C_COMPILER=clang \
```
Comment (ericmlujan) [inline cpp/Makefile:33]: Should we update the env vars in our build containers to set `CXX` and `CC` to clang, so that our official builds still use it over gcc? I checked that in our docker images, `c++` and `cc` (which CMake invokes by default if the user doesn't specify anything) are aliases for gcc.

Comment (ericmlujan) [reply cpp/Makefile:33]: Separately, agree we should have a GCC test for CI, as @amacneil suggested

File: cpp/foxglove/include/foxglove/server/parameter.hpp [hunk 2]
```diff
@@ -300,18 +257,8 @@ class ParameterView final {
...
-  /// @brief Checks whether the paramter value is an dictionary of generic
-  /// values.
-  template<>
-  [[nodiscard]] bool isDict<ParameterValueView>() const noexcept {
-    auto value = this->value();
-    return value.has_value() && value->is<ParameterValueView::Dict>();
-  }
-
   /// @brief Checks whether the parameter value is a byte array.
-  [[nodiscard]] bool isByteArray() const noexcept {
```
Comment (ericmlujan) [inline cpp/foxglove/include/foxglove/server/parameter.hpp:312]: Was there a particular reason you moved this as well, given that it isn't an explicit initialization? Or just cleaning things up as you went?

**Review by ericmlujan — APPROVED** [review]
LGTM

File: cpp/foxglove/include/foxglove/server/parameter.hpp (hunk 2 above)
Comment (jtbandes) [reply cpp/foxglove/include/foxglove/server/parameter.hpp:312]: The use of `this->is<std::vector<std::byte>>()` triggered some error about the specialization being defined after the instantiation, so I had to move the function body down below where the `vector<byte>` instantiation was defined.... at least I think that's what was going on 😓

File: cpp/Makefile (hunk 1 above)
Comment (jtbandes) [reply cpp/Makefile:33]: I guess my thinking was that since we don't actually publish the built **C++** artifacts, I didn't see a reason to keep it set to clang... or what did you mean by "official builds"? are you saying we should keep this because we want to test clang on all platforms as well as testing gcc?  (I think by default we are getting clang for the macos builds, gcc for the linux builds and msvc for the windows builds – but haven't verified this)

**Comment by jtbandes** [comment]
> Can we add to CI?

to clarify, I removed some vars that were forcing clang in CI -- the linux builds in CI are now using GCC. You can see it in the logs here: https://github.com/foxglove/foxglove-sdk/actions/runs/16013991239/job/45177082447?pr=516#step:8:22

File: cpp/Makefile (hunk 1 above)
Comment (ericmlujan) [reply cpp/Makefile:33]: That's fair. I suppose I was suggesting we explicitly test clang on macOS and Linux, and just add an additional linux GCC build, but maybe that's overkill. That said, given that this is a public SDK, I think we should be explicit on which compiler/OS pairs we officially support/test against, and document that somewhere

Comment (jtbandes) [reply cpp/Makefile:33]: Added new builds so we are now building both clang & gcc on linux

File: cpp/foxglove/include/foxglove/server/parameter.hpp [hunk 3]
```diff
@@ -435,6 +355,121 @@ class ParameterView final {
...
+// Template specializations for ParameterView
+//
+// Documented manually as tparams because specializations are merged:
+// https://github.com/doxygen/doxygen/issues/9468
+
+/// @fn ParameterView::is<std::string_view>()
+/// @tparam std::string_view Checks whether the parameter value is a string.
+
+/// @fn ParameterView::is<std::string>()
+/// @note foobar
```
Comment (bryfox) [inline cpp/foxglove/include/foxglove/server/parameter.hpp]: I'm sorry, I was playing around with different ways to render these docs in #518 and neglected to remove this 😅 

```suggestion
```
